<a href="https://colab.research.google.com/github/luizignacio3452/QuimeraLog/blob/main/RAIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
caminho_arquivo = '/content/drive/MyDrive/Data/RAIS/RAIS_DADOS.txt'

In [ ]:
amostra = pd.read_csv(caminho_arquivo, sep=';', encoding='Latin_1', nrows=5)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Data/RAIS/RAIS_DADOS.txt'

In [ ]:
amostra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Bairros SP                 5 non-null      int64
 1   Bairros Fortaleza          5 non-null      int64
 2   Bairros RJ                 5 non-null      int64
 3   CNAE 2.0 Classe            5 non-null      int64
 4   CNAE 95 Classe             5 non-null      int64
 5   Distritos SP               5 non-null      int64
 6   Qtd Vínculos CLT           5 non-null      int64
 7   Qtd Vínculos Ativos        5 non-null      int64
 8   Qtd Vínculos Estatutários  5 non-null      int64
 9   Ind Atividade Ano          5 non-null      int64
 10  Ind CEI Vinculado          5 non-null      int64
 11  Ind Estab Participa PAT    5 non-null      int64
 12  Ind Rais Negativa          5 non-null      int64
 13  Ind Simples                5 non-null      int64
 14  Município                  5 non-null      int64
 15  Natureza Jurídica          5 non-null      int64
 16  Regiões Adm DF             5 non-null      int64
 17  CNAE 2.0 Subclasse         5 non-null      int64
 18  Tamanho Estabelecimento    5 non-null      int64
 19  Tipo Estab                 5 non-null      int64
 20  Tipo Estab.1               5 non-null      object
 21  UF                         5 non-null      int64
 22  IBGE Subsetor              5 non-null      int64
 23  CEP Estab                  5 non-null      int64
dtypes: int64(23), object(1)
memory usage: 1.1+ KB

In [ ]:
amostra.head(5)

,Bairros SP,Bairros Fortaleza,Bairros RJ,CNAE 2.0 Classe,CNAE 95 Classe,Distritos SP,Qtd Vínculos CLT,Qtd Vínculos Ativos,Qtd Vínculos Estatutários,Ind Atividade Ano,...,Município,Natureza Jurídica,Regiões Adm DF,CNAE 2.0 Subclasse,Tamanho Estabelecimento,Tipo Estab,Tipo Estab.1,UF,IBGE Subsetor,CEP Estab
0,9997,9997,9997,47725,52418,9997,4,4,0,1,...,110028,2062,9997,4772500,2,1,Cnpj,11,16,76940000
1,9997,9997,9997,69117,74110,9997,1,1,0,1,...,110030,2321,9997,6911701,2,1,Cnpj,11,19,76980016
2,9997,9997,9997,47121,52132,9997,3,3,0,1,...,110004,2135,9997,4712100,2,1,Cnpj,11,16,76960068
3,9997,9997,9997,45412,50415,9997,7,7,0,1,...,110002,2135,9997,4541206,3,1,Cnpj,11,16,76870317
4,9997,9997,9997,47831,52493,9997,4,4,0,1,...,110004,2062,9997,4783102,2,1,Cnpj,11,16,76963887

In [ ]:
codigo_sjc = 354990
tamanho_bloco = 100000
rais_sjc = []

for chunk in pd.read_csv(caminho_arquivo, sep=';', encoding='latin_1', chunksize=tamanho_bloco, low_memory=False):
    filtro = chunk[chunk['Município'] == codigo_sjc]
    empresas_sjc.append(filtro)

rais_sjc = pd.concat(empresas_sjc, ignore_index=True)

In [ ]:
amostra.head(100)

,Bairros SP,Bairros Fortaleza,Bairros RJ,CNAE 2.0 Classe,CNAE 95 Classe,Distritos SP,Qtd Vínculos CLT,Qtd Vínculos Ativos,Qtd Vínculos Estatutários,Ind Atividade Ano,...,Município,Natureza Jurídica,Regiões Adm DF,CNAE 2.0 Subclasse,Tamanho Estabelecimento,Tipo Estab,Tipo Estab.1,UF,IBGE Subsetor,CEP Estab
0,9997,9997,9997,47725,52418,9997,4,4,0,1,...,110028,2062,9997,4772500,2,1,Cnpj,11,16,76940000
1,9997,9997,9997,69117,74110,9997,1,1,0,1,...,110030,2321,9997,6911701,2,1,Cnpj,11,19,76980016
2,9997,9997,9997,47121,52132,9997,3,3,0,1,...,110004,2135,9997,4712100,2,1,Cnpj,11,16,76960068
3,9997,9997,9997,45412,50415,9997,7,7,0,1,...,110002,2135,9997,4541206,3,1,Cnpj,11,16,76870317
4,9997,9997,9997,47831,52493,9997,4,4,0,1,...,110004,2062,9997,4783102,2,1,Cnpj,11,16,76963887

Warning: Total number of columns (24) exceeds max_columns (20) limiting to first (20) columns.